### ISSUE TITLE
Pregunta seria

### ISSUE THREAD

**Issue by VictoRPiles** [nandopiles/1DAM_Programacion#1]
Una cosa no se fer un bucle while i tinc exàmen demà, vaig a suspendre? 👍🏼

**Comment by nandopiles** [comment]
Bona tarda Víctor, no, als bùcles while estàn Deprecated i no deurîes de gastar-los. Utilitza varios ifs mìllor.
Que vaja molt bé l'exàmen i anrecordat qua llibertat als prassus!!
